#!/bin/sh
set -e

echo "APP_ENV = ${APP_ENV}"
#test -d vendor && php bin/console debug:dotenv #&& make migrate

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- php-fpm "$@"
fi

exec "$@"